ProjectWebFinal/ProjectWebFinal/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectWebFinal.Models;
using System.Text;

namespace ProjectWebFinal.Controllers {
    [Authorize]
    public class ManagerController : Controller {
        HttpClientHandler _clientHandler = new HttpClientHandler();

        public ManagerController() {
            _clientHandler.ServerCertificateCustomValidationCallback =
                (sender, cert, chain, sslPolicyErrors) => { return true; };
        }

        // GET: CallManagerController
        public async Task<ActionResult> Index(String SearchText) {
            List<Manager>? managers = await GetManagers();
            if (!string.IsNullOrEmpty(SearchText))
            {

                managers = managers!.Where(x => x.FirstName!.ToLower().Contains(SearchText.ToLower()) || x.LastName!.ToLower().Contains(SearchText.ToLower())).ToList();

            }


            return View(managers);
        }

  

        [HttpGet]
        public async Task<List<Manager>?> GetManagers() {
            List<Manager>? managers = new List<Manager>();
            using (var httpClient = new HttpClient(_clientHandler)) {
                using (var response = await httpClient.GetAsync("https://localhost:7085/api/Manager")) {
                    string strJson = await response.Content.ReadAsStringAsync();
                    managers = JsonConvert.DeserializeObject<List<Manager>>(strJson);
                }
            }
            return managers;
        }

        // GET: ManagerController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Manager? manager = new Manager();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:7085/api/Manager/id?id="+id))
                {
                    string strJson = await response.Content.ReadAsStringAsync();
                    manager = JsonConvert.DeserializeObject<Manager>(strJson);
                }
            }
            return View(manager);
        }

        // GET: ManagerController/Create
        public ActionResult Create() {
            return View();
        }

        // POST: ManagerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Manager manager) {
            try {
                Manager? mng = new Manager();
                using (var httpClient = new HttpClient(_clientHandler))
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(manager), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("https://localhost:7085/api/Manager", content))
                    {
                        string strJson = await response.Content.ReadAsStringAsync();
                        mng = JsonConvert.DeserializeObject<Manager>(strJson);
                        if (ModelState.IsValid)
                        {
                            return RedirectToAction(nameof(Index));
                        }
                    }
                }
                return View(mng);
            }
            catch
            {
                return View();
            }
        }

        // GET: ManagerController/Edit/5
        public async Task<ActionResult> Edit(int id) {
            Manager? manager = new Manager();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:7085/api/Manager/id?id=" + id))
                {
                    string strJson = await response.Content.ReadAsStringAsync();
                    manager = JsonConvert.DeserializeObject<Manager>(strJson);
                }
            }
            return View(manager);
        }

        // POST: ManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id,Manager manager) {
            Manager mng = new Manager();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(manager), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:7085/api/Manager/" + id,content))
                {
                    
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ManagerController/Delete/5
        public async Task<ActionResult> Delete(int id) {
            string del = "";
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:7085/api/Manager/" + id))
                {
                    del = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: ManagerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            } catch {
                return View();
            }
        }



    }
}

ProjectWebFinal/ProjectWebFinal/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectWebApiFinal.Models;
using ProjectWebFinal.Models;
using System.Text;


namespace ProjectWebFinal.Controllers {
    [Authorize]
    public class MovieController : Controller {
        HttpClientHandler _clientHandler = new HttpClientHandler();

        

        public MovieController() {
            _clientHandler.ServerCertificateCustomValidationCallback =
                (sender, cert, chain, sslPolicyErrors) => { return true; };
        }

        // GET: MovieController
        public async Task<ActionResult> Index(String SearchText) {
            List<Movie>? movies = await GetMovies();
            if (!string.IsNullOrEmpty(SearchText))
            {
                movies = movies!.Where(x => x.Title!.ToLower().Contains(SearchText.ToLower()) || x.Year!.ToLower().Contains(SearchText.ToLower())).ToList();
            }
            return View(movies);
        }



        [HttpGet]
        public async Task<List<Movie>?> GetMovies() {
            List<Movie>? movies = new List<Movie>();
            using (var httpClient = new HttpClient(_clientHandler)) {
                using (var response = await httpClient.GetAsync("https://localhost:7085/api/Movie")) {
                    string strJson = await response.Content.ReadAsStringAsync();
                    movies = JsonConvert.DeserializeObject<List<Movie>>(strJson);
                }
            }
            return movies;
        }

        // GET: MovieController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            {
                Movie? movie = new Movie();
                using (var httpClient = new HttpClient(_clientHandler))
                {
                    using (var response = await httpClient.GetAsync("https://localhost:7085/api/Movie/id?id=" + id))
                    {
                        string strJson = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(strJson);
                    }
                }
                return View(movie);
            }
        }

        // GET: MovieController/Create
        public ActionResult Create() {
            return View();
        }

        // POST: MovieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Movie model, IFormFile formFile) {
            string? path = UploadImage(formFile);



            try {
                if (path == null) {
                    throw new Exception();
                } else { 
                    Movie newMovie = new Movie() {
                        Title = model.Title,
                        Year = model.Year,
                        Poster = path
                    };
                Movie? movie = new Movie();
                using (var httpClient = new HttpClient(_clientHandler)) {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(newMovie), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("https://localhost:7085/api/Movie", content)) {
                        string strJson = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(strJson);
                        if (ModelState.IsValid) {
                            return RedirectToAction(nameof(Index));
                        }
                    }
                }
                TempData["imgError"] = "โปรดเลือกรูปภาพ";
                return View(movie);
                }
            } catch {
                TempData["imgError"] = "โปรดเลือกรูปภาพ";
                return View(model);
            }
        }

        [HttpPost]
        public string? UploadImage(IFormFile file) {
            Random rnd = new Random();
            try {
                if (file != null) {
                    int r = rnd.Next();
                    string fileName = file.FileName;
                    fileName = Path.GetFileName(fileName);
                    string uploadpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", r+fileName);
                    var stream = new FileStream(uploadpath, FileMode.Create);
                    file.CopyToAsync(stream);
                    return "~/images/"+r+fileName;
                } else {
                    return null;
                }
            } catch {
                return null;
            }
        }

        // GET: MovieController/Edit/5
        public async Task<ActionResult> Edit(int id) {
            Movie? movie = new Movie();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://localhost:7085/api/Movie/id?id=" + id))
                {
                    string strJson = await response.Content.ReadAsStringAsync();
                    movie = JsonConvert.DeserializeObject<Movie>(strJson);
                }
            }
            return View(movie);
        }
        
        // POST: MovieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Movie movie, IFormFile file)
        {
            
            string? path = UploadImage(file);

            if (path == null) {
                List<Movie> mm = await GetMovies();
                var m = mm.First(x => x.Id == id);
                movie.Poster = m.Poster;
            } else { 
                movie.Poster = path;
            }

            try {
                Movie mv = new Movie();
                using (var httpClient = new HttpClient(_clientHandler))
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync("https://localhost:7085/api/Movie/" + id, content))
                    {
                        string strJson = await response.Content.ReadAsStringAsync();
                        mv = JsonConvert.DeserializeObject<Movie>(strJson);
                        if (ModelState.IsValid) {
                            return RedirectToAction(nameof(Index));
                        }
                    }
                }
            return RedirectToAction(nameof(Index));
            } catch {
                TempData["imgError"] = "โปรดเลือกรูปภาพ";
                return View(movie);
            }
        }

        // GET: MovieController/Delete/5
        public async Task<ActionResult> Delete(int id) {
            string del = "";
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:7085/api/Movie/" + id))
                {
                    del = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: MovieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                return RedirectToAction(nameof(Index));
            } catch {
                return View();
            }
        }
    }
}

ProjectWebFinal/ProjectWebFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectWebFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectWebFinal.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mali:wght@400;500;600&display=swap" rel="stylesheet">

</head>
<body style="background-color:#031633;">
    @if (User.Identity.IsAuthenticated) {

        <nav class="navbar navbar-expand-sm fixed-top navbar-light border-bottom box-shadow text-white" style="background-color:#020E22;">
        <div class="container my-3">
            <p class="navbar-brand text-white" style="margin: 0;">ProjectWebFinal</p>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav mx-3">
                    <li class="nav-item me-3 nav-link">
                            <a asp-action="Index" class="text-white" asp-controller="Manager" style="text-decoration: none;">ข้อมูลผู้จัดการ</a>

                    </li>
                    <li class="nav-item nav-item me-3 nav-link">

                            <a asp-action="Index" class="text-white" asp-controller="Movie" style="text-decoration: none;">ภาพยนตร์</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item">
                        <div>
                            <span class="px-2">@User.Identity.Name</span>
                            <a class="btn btn-outline-danger" asp-action="Logout" asp-controller="Account">ออกจากระบบ</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav> 
    }
    <div class="container mt-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
        integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
        crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectWebFinal/ProjectWebFinal/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Account</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectWebFinal.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mali:wght@400;500;600&display=swap" rel="stylesheet">
    <style>
        body {
            background-image: url("https://www.wallpapertip.com/wmimgs/15-155756_movie-ppt-backgrounds-powerpoint-backgrounds-movie-background.jpg");
            background-attachment: fixed;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>
<body>
    @RenderBody()
        <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
        integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
        crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectWebFinal/ProjectWebFinal/Views/Shared/_Layout_Movie.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectWebFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectWebFinal.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mali:wght@400;500;600&display=swap" rel="stylesheet">

    <style>

        .card {
            flex-direction: row;
        }

        .card img {
            height: 400px;
            width: 270px;
        }
    </style>
</head>
<body style="background-color:#031633;">
    @if (User.Identity.IsAuthenticated) {

        <nav class="navbar navbar-expand-sm navbar-light border-bottom box-shadow text-white" style="background-color:#020E22;">
        <div class="container my-3">
            <p class="navbar-brand text-white" style="margin: 0;">ProjectWebFinal</p>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav mx-3">
                    <li class="nav-item me-3 nav-link">
                            <a asp-action="Index" class="text-white" asp-controller="Manager" style="text-decoration: none;">ข้อมูลผู้จัดการ</a>

                    </li>
                    <li class="nav-item nav-item me-3 nav-link">

                            <a asp-action="Index" class="text-white" asp-controller="Movie" style="text-decoration: none;">ภาพยนตร์</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item">
                        <div>
                            <span class="px-2">@User.Identity.Name</span>
                            <a class="btn btn-outline-danger" asp-action="Logout" asp-controller="Account">ออกจากระบบ</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav> 
    }
    @RenderBody()
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
        integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc"
        crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>